name: Discord Announcement

on:
  release:
    types:
      - published
jobs:
  slack:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      VERSION: ''
    steps:
      - name: Get version
        id: get_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
      - name: Announce on discord
        id: announce_discord
        run: |
          ./.github/workflow_scripts/announce_discord.sh   --webhook-url $DISCORD_WEBHOOK
        env:
          SLACK_WEBHOOKS: ${{ env.DISCORD_WEBHOOK }}
